### ISSUE TITLE
ABCL: CL command returns success in case of uncaught exception

### ISSUE THREAD

**Issue by metawilm** [sionescu/CIM#66]
When ABCL encounters a NullPointerException and aborts execution, still exit code 0 is returned from the CL command. This means e.g. Travis considers the test a success. I think it should return a nonzero value to indicate failure instead.
 
Example Travis-CI job log: https://travis-ci.org/metawilm/cl-python/jobs/210320828

The Lisp form being evaluated looks essentially like:
```
(warn "Before ignore-errors")
(ignore-errors (...test code...))
(warn "After ignore-errors")
```

The output says:
```
WARNING: Before ignore-errors
...
Exception in thread "interpreter" java.lang.NullPointerException
	at org.armedbear.lisp.StandardObject$pf_standard_instance_access.execute(StandardObject.java:446)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:814)
        ...
The command "cl -e ..." exited with 0.
```
without showing the "After ignore-errors" warning, indicating the NPE was not caught at the Lisp level.

**Comment by metawilm** [comment]
Wrapping the test form inside UNWIND-PROTECT does lead to the Lisp cleanup forms being evaluated after the Java NPE. So it's possible to manually return a desired exit code there. But the exception backtrace is then not printed anymore, so this is not ideal.
Example: https://travis-ci.org/metawilm/cl-python/jobs/210332741

**Comment by KeenS** [comment]
@metawilm Thank you for reporting bugs. However as described in README, CIM is deprecated and no more be maintained.
If you want to run tests on various CL impls at CI, consider using [roswell](https://github.com/roswell/roswell)
